name: 'AlgoSec’s IaC solution'
description: 'Extensible security plugin platform that checks code for potential vulnerabilities before any commits to a repository'
author: 'alon.noy@algosec.com'
branding:
  icon: 'activity'
  color: 'blue'
runs:
  using: 'node16'
  main: 'dist/index.js'
