name: 'Algosec Risk Analysis'
description: 'This GitHub Action runs Algosec Risk Analysis against an Infrastructure-as-Code repository.'
author: 'alon.noy@algosec.com'
runs:
  using: 'node16'
  main: 'dist/index.js'
