name: 'IAC connectivity risk analysis'
description: 'Extensible security plugin platform that checks code for potential vulnerabilities before any commits to a repository.'
author: 'Algosec'
branding:
  icon: 'activity'
  color: 'blue'
runs:
  using: 'docker'
  image: 'docker://public.ecr.aws/algosec/connectivity-risk-analysis:1.0.23'
  entrypoint: 'iac-risk-analysis'
